### ISSUE TITLE
Error: locator.click: Error: strict mode violation: locator('li.wp-menu-open > ul.wp-submenu > li:has-text("Orders")')

### ISSUE THREAD

**Issue by rajausman786** [woocommerce/qit-cli#199]
I am getting this error message in QIT test woo-e2e, my plugin menu name is "Bulk Edit Orders", this name shown under WooCommerce as sub menu. due to "Orders" word in the menu QIT woo-e2e test is getting failed.

**Comment by Luc45** [comment]
Thanks for flagging this to us.

The Woo E2E test covers around 400 user flows. If 1 of them fails because of incompatibility such as these, you still get coverage for the other 399 user flows. It is expected that some extensions might fail some user flows because of changes to the UI/HTML structure, and that is fine.

Still, we try to make the test as compatible as possible, so we will look into it as well, thanks for flagging.

**Comment by rajausman786** [comment]
Thanks for your reply and looking into this,

**Comment by Luc45** [comment]
That should be solved on Woo 9.3.0 release, closing this.
